### ISSUE TITLE
TEI References - Missing excerpts

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-instance-tibschol#130]
|TEI ID|RELATION PK|Relation|Subject PK|Object PK|
|--|--|--|--|--|
|ex1301_1232023-06-28|607|PersonAuthorOfWork|3839|4550|
|ex76012024-09-1612-18-36|991|PersonAuthorOfWork|4080|5209|
|ex1301_20072023-06-28|1764|PersonOwnerOfInstance|4551|4549|
|ex502-19072023-05-34|4154|PersonRefersWithNameToTheViewsOfPerson|3806|3745|
|ex502-19072023-05-34|4158|PersonRefersWithNameToTheViewsOfPerson|3806|4182|
|ex5032023-05-2516-45-34|4159|PersonRefersWithNameToTheViewsOfPerson|3806|3786|
|ex45042024-08-2914-22-28|4126|PersonRefersWithoutNameToTheViewsOfPerson|6802|3892|
|ex45042024-08-2914-22-28b|4126|PersonRefersWithoutNameToTheViewsOfPerson|6802|3892|
|ex45042024-08-2914-22-28c|4126|PersonRefersWithoutNameToTheViewsOfPerson|6802|3892|
|ex45042024-08-2914-22-28h|4126|PersonRefersWithoutNameToTheViewsOfPerson|6802|3892|

**Comment by phugon** [comment]
Corrected.
