### ISSUE TITLE
Relations - Review

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-instance-tibschol#211]
Updated status after #228 

|Relation | Number of records|
|-- | --|
|PersonAuthorOfWork|880|
|PersonStudentOfPerson|762|
|WorkHasAsAnInstanceInstance|679|
|PersonActiveAtPlace|570|
|WorkCommentaryOnWork|442|
|PersonDirectPredecessorInLineageOfPerson|157|
|PlaceIsLocatedWithinPlace|132|
|WorkComposedAtPlace|114|
|PersonHasOtherTypeOfPersonalRelationToPerson|92|
|PersonRefersWithNameToTheViewsOfPerson|90|
|PersonRefersWithoutNameToTheViewsOfPerson|78|
|PersonOrdinatorOfPerson|75|
|InstanceIsCopiedFromInstance|65|
|PersonScribeOfInstance|54|
|PersonOwnerOfInstance|37|
|InstanceCopiedWrittenDownAtPlace|31|
|PersonParentOfPerson|29|
|PersonStudiedWork|28|
|PersonTranslatorOfWork|26|
|PersonTeachesWork|24|
|PersonPrompterOfWork|19|
|PersonSiblingOfPerson|16|
|PersonUncleMaternalPaternalOfPerson|15|
|PersonBiographerOfPerson|14|
|PersonRequestorOfPerson|14|
|PersonBiographedInWork|10|
|WorkRecordsTheTeachingOfPerson|8|
|PersonAddresseeOfWork|5|
|PersonSponsorOfInstance|4|
|WorkTaughtAtPlace|2|
|PersonHasOtherRelationWithInstance|1|
|WorkContainsCitationsOfWork|0|

**Comment by phugon** [comment]
Also to be deleted: the relations:
WorkQuotesWithNameTheViewsOfPerson
WorkQuotesWithoutNameTheViewsOfPerson
which are now (0)

**Comment by phugon** [comment]
delete relation:
PersonDiscipleOfPerson

(to be continued)

**Comment by phugon** [comment]
delete relation 
Person annotator of Instance
